[workspace]
resolver = "2"
members = [
    "abyss_lexer", "abyss_parser",
]


[package]
name = "abyss"
version = "0.1.0"
edition = "2024"

[dependencies]
abyss_lexer = { path = "./abyss_lexer" }
abyss_parser = { path = "./abyss_parser" }
