[package]
name = "abyss_codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
abyss_lexer = { path = "../abyss_lexer" }
abyss_parser = { path = "../abyss_parser" }

cranelift = "0.108.0"
cranelift-jit = "0.108.0"
cranelift-module = "0.108.0"
